_BASE_: "viper_semantic_cerberus.yaml"
MODEL:
  META_ARCHITECTURE: "ClipSimpleAPSCerberusPS"
PERSON_SEARCH:
  REID:
    USE_APS_CERBERUS_BRANCH: True
    APS_CERBERUS_LOSS_WEIGHT: 1.0
    APS_CERBERUS_GROUP_SCORE_WEIGHT: 1.0
    APS_CERBERUS_DETACH_VISUAL_INPUTS: False
    CERBERUS_REGION_BRANCH_MODE: "sfan"
SOLVER:
  LR_FACTORS: [5.0, 5.0, 1.0]
  LR_GROUP_REGEX: ["proposal_generator.+", "roi_heads.box_predictor.+", "aps_branch.+"]
TEST:
  SEARCH_PROTOCOL: "aps"
OUTPUT_DIR: "outputs/viper/PRW/viper_aps_cerberus_prw"
