_BASE_: "viper_semantic_cerberus_branch_only.yaml"
MODEL:
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
SOLVER:
  IMS_PER_BATCH: 44
  BASE_LR: 0.0000444
OUTPUT_DIR: "outputs/viper/PRW/viper_semantic_cerberus_two_stage"
