_BASE_: "viper_semantic_cerberus.yaml"
PERSON_SEARCH:
  REID:
    CERBERUS_REGION_BRANCH_MODE: "cerberus"
    SCHEMA_PATH: "data_text/PRW/generated_schema.json"
SOLVER:
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 18
  BASE_LR: 0.0000225
INPUT:
  ATTRIBUTE_ANNOTATIONS_PATH: "data_text/PRW/prw_Final_Complete_cleaned_train.json"
  TEST_ATTRIBUTE_ANNOTATIONS_PATH: "data_text/PRW/prw_Final_Complete_cleaned_test.json"
OUTPUT_DIR: "outputs/viper/PRW/viper_semantic_cerberus_branch"
